"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.table = void 0;
/**
 * Renders a table generated by steelbreeze/landscape to an HTML element
 * @param tableData
 * @param elementId
 */
function table(tableData, elementId, className) {
    const tableElement = document.createElement('table');
    tableElement.id = elementId;
    tableElement.classList.add(className);
    for (const rowData of tableData) {
        tableElement.appendChild(row(rowData));
    }
    return tableElement;
}
exports.table = table;
// render a row in a table
function row(rowData) {
    const rowElement = document.createElement('tr');
    for (const cellData of rowData) {
        rowElement.appendChild(cell(cellData));
    }
    return rowElement;
}
// render a cell in a table with a child div
function cell(cellData) {
    const cellElement = document.createElement(cellData.style.includes('axis') ? 'th' : 'td');
    cellElement.colSpan = cellData.cols;
    cellElement.rowSpan = cellData.rows;
    cellElement.className = `cell ${cellData.style}`;
    const divElement = document.createElement('div');
    divElement.appendChild(document.createTextNode(cellData.altText || cellData.text));
    cellElement.appendChild(divElement);
    return cellElement;
}
