import { Row } from '@steelbreeze/pivot';
import { Cell } from '.';
/**
 * Renders a table generated by steelbreeze/landscape to an HTML element
 * @param tableData
 * @param elementId
 */
export declare function table<TRow extends Row>(tableData: Array<Array<Cell<TRow>>>, elementId: string, className: string): HTMLTableElement;
