import { Cell } from '.';
/**
 * Renders a table generated by steelbreeze/landscape to an HTML element
 * @param tableData
 * @param elementId
 */
export declare function table(tableData: Array<Array<Cell>>, elementId: string, className: string): HTMLTableElement;
