"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.table = void 0;
/**
 * Renders a table generated by steelbreeze/landscape to an HTML element
 * @param table
 * @param elementId
 */
function table(table, elementId) {
    const targetElement = document.getElementById(elementId);
    if (targetElement) {
        const tableElement = document.createElement('table');
        tableElement.id = elementId;
        tableElement.classList.add('landscape');
        for (const row of table) {
            const rowElement = document.createElement('tr');
            for (const cell of row) {
                const cellElement = document.createElement(cell.className.includes('axis') ? 'th' : 'td');
                cellElement.colSpan = cell.colSpan;
                cellElement.rowSpan = cell.rowSpan;
                cellElement.className = `cell ${cell.className}`;
                const divElement = document.createElement('div');
                divElement.appendChild(document.createTextNode(cell.text));
                cellElement.appendChild(divElement);
                rowElement.appendChild(cellElement);
            }
            tableElement.appendChild(rowElement);
        }
        targetElement.replaceWith(tableElement);
    }
}
exports.table = table;
