"use strict";
exports.__esModule = true;
var getAxis_1 = require("./getAxis");
exports.getAxis = getAxis_1.getAxis;
var getOptimalAxes_1 = require("./getOptimalAxes");
exports.getOptimalAxes = getOptimalAxes_1.getOptimalAxes;
exports.flexOrder = getOptimalAxes_1.flexOrder;
var getTable_1 = require("./getTable");
exports.getTable = getTable_1.getTable;
var getHTML_1 = require("./getHTML");
exports.getHTML = getHTML_1.getHTML;
var filters_1 = require("./filters");
exports.filter = filters_1.filter;
exports.filterByDate = filters_1.filterByDate;
